# Generated by Django 3.0.3 on 2020-09-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, null=True)),
                ('a_pos', models.CharField(choices=[('NEBULA', 'N'), ('GAMORA', 'G'), ('LOKI', 'L'), ('ROCKET', 'R'), ('HULK', 'H'), ('THOR', 'T'), ('CAP', 'Q'), ('BUCKY', 'B')], max_length=25, null=True)),
                ('a_num', models.CharField(choices=[('90', '90'), ('92', '92'), ('93', '93'), ('96', '96')], max_length=25, null=True)),
                ('play', models.ImageField(blank=True, default='default.png', upload_to='answers/')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('q_text', models.CharField(help_text='Enter the question that you want displayed', max_length=250, null=True, verbose_name='Question')),
                ('q_pos', models.CharField(choices=[('NEBULA', 'N'), ('GAMORA', 'G'), ('LOKI', 'L'), ('ROCKET', 'R'), ('HULK', 'H'), ('THOR', 'T'), ('CAP', 'Q'), ('BUCKY', 'B')], max_length=25, null=True)),
                ('q_num', models.CharField(choices=[('90', '90'), ('92', '92'), ('93', '93'), ('96', '96')], max_length=25, null=True)),
            ],
        ),
    ]
